
const curiosidades = [
  "🐘 O elefante é o único animal que não consegue pular.",
  "🦷 Os dentes dos tubarões se regeneram ao longo da vida.",
  "🌙 Na Lua, você pesa cerca de 1/6 do que pesa na Terra.",
  "🦇 Morcegos sempre viram para a esquerda ao sair da caverna.",
  "🧠 O cérebro humano é mais ativo durante a noite do que durante o dia.",
  "🦋 As borboletas conseguem ver cores que os humanos não veem.",
  "🐦 Beija-flores podem bater as asas até 80 vezes por segundo.",
  "🐍 Cobras podem sentir vibrações pelo chão com a mandíbula.",
  "🐔 Galinhas lembram de mais de 100 rostos diferentes, humanos ou não.",
  "🌈 Um arco-íris na verdade é um círculo, mas a Terra bloqueia a metade inferior.",
  "🕷️ As aranhas não conseguem andar de cabeça para baixo no vidro liso.",
  "💧 A água quente pode congelar mais rápido que a fria (Efeito Mpemba).",
  "🪐 Um dia em Vênus dura mais do que um ano de Vênus.",
  "🐢 Tartarugas podem viver mais de 150 anos.",
  "🦈 Tubarões existem há mais tempo que as árvores.",
  "🦎 Lagartixas podem regenerar a cauda quando perdem.",
  "🎈 O hélio faz a voz ficar fina porque altera a velocidade do som nas cordas vocais.",
  "🐙 Polvos têm três corações e sangue azul.",
  "🐧 Pinguins têm joelhos, mas estão escondidos sob a gordura.",
  "🐼 Pandas passam cerca de 12 horas por dia comendo bambu.",
  "🦍 Gorilas conseguem aprender linguagem de sinais.",
  "🌋 O ponto mais profundo da Terra é mais fundo que o Everest é alto.",
  "🦵 O osso mais forte do corpo é o fêmur.",
  "🐕 Cães podem sentir o cheiro do medo.",
  "🌊 O som viaja cinco vezes mais rápido na água do que no ar.",
  "🔥 As chamas não têm sombra.",
  "🧊 Antártica é o maior deserto do mundo.",
  "🎵 O som mais alto já registrado foi a erupção do Krakatoa em 1883.",
  "🕶️ Os olhos usam mais músculos do que qualquer outra parte do corpo.",
  "💨 Você respira cerca de 20 mil vezes por dia.",
  "🐾 Gatos têm 32 músculos em cada orelha.",
  "💡 Edison não inventou a lâmpada, ele aperfeiçoou-a.",
  "🕰️ Os romanos antigos usavam urina como produto de limpeza.",
  "📱 Existem mais celulares no mundo do que pessoas.",
  "🍌 Bananas são naturalmente radioativas.",
  "🦆 Patos não fazem eco — e ninguém sabe o porquê com certeza.",
  "🚀 O GPS não funcionaria corretamente sem a Teoria da Relatividade.",
  "👃 O olfato humano pode detectar mais de 1 trilhão de cheiros.",
  "🥶 O ponto mais frio já registrado foi -89,2 °C na Antártida.",
  "💻 O primeiro computador ocupava uma sala inteira.",
  "👅 A língua humana tem entre 2.000 e 8.000 papilas gustativas.",
  "🔋 A energia de um relâmpago poderia acender 100 lâmpadas por dia.",
  "🧃 Um litro de leite pesa mais que um litro de água.",
  "🐎 O cavalo mais rápido já registrado atingiu 88 km/h.",
  "🎮 O primeiro videogame foi criado em 1958.",
  "🔭 O telescópio Hubble tem cerca de 13 metros de comprimento.",
  "👣 Existem mais bactérias na sua boca do que pessoas no mundo.",
  "🥚 A casca de ovo é porosa, por isso os ovos absorvem cheiros.",
  "🕳️ Buracos negros não “sugam” — eles atraem por gravidade extrema.",
  "📖 O livro mais vendido da história é a Bíblia.",
  "🐘 O elefante é o único animal que não consegue pular.",
  "🌍 A Terra não é perfeitamente redonda, ela é levemente achatada nos polos.",
  "🦁 Os leões podem dormir até 20 horas por dia.",
  "🍯 O mel é o único alimento que não estraga.",
  "🧠 O cérebro humano é mais ativo à noite do que durante o dia.",
  "🦋 As borboletas sentem o gosto pelos pés.",
  "🚀 O primeiro e-mail da história foi enviado em 1971.",
  "🌕 A Lua está se afastando da Terra cerca de 3,8 cm por ano.",
  "🔋 A bateria de lítio foi inventada em 1985.",
  "🐙 Os polvos têm três corações e sangue azul."
];

async function commandCuriosidades(enviarMensagem) {
  const curiosidade = curiosidades[Math.floor(Math.random() * curiosidades.length)];
  await enviarMensagem(curiosidade);
}

module.exports = { commandCuriosidades };